name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-pio
          path: |
            ~/.cache/pip
            ~/.platformio/.cache

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Install Packages
        run: pio pkg update && pio pkg install

      - name: Build All
        run: pio run

      # .pio/build/[device_name]/firmware.uf2 を build/*/seismometer-[device_name].uf2 にリネーム
      - name: Move Artifacts
        run: |
          PLATFORMS=`ls .pio/build`
          for PLATFORM in $PLATFORMS; do
            mkdir -p build/$PLATFORM
            mv .pio/build/$PLATFORM/firmware.uf2 build/$PLATFORM/seismometer-$PLATFORM.uf2
          done

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: eqis-1-esp32s3
          path: .pio/build/eqis-1-esp32s3
